[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cryptominer"
version = "0.0.0"
authors = [
  { name="i44p", email="jsbbdjzjsjawk@gmail.com" },
]
readme = "README.md"
requires-python = ">=3.7"